name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.16.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.16.x
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test

  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  audit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.16.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.x
          cache: 'npm'
      - run: npm ci
      - run: npm audit --json > audit.json
      - uses: actions/upload-artifact@v4
        with:
          name: audit-report
          path: audit.json
  
  lint:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 22.16.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      
  
  
    
